version: '3'
services:
    web:
        image: nginx:latest
        ports:
          - "${HTTP_PORT:-80}:80"
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
          - ./legacy:/legacy
    php:
        build:
            context: .
            dockerfile: docker/php.dockerfile
        volumes:
          - ./legacy:/legacy
    mysql:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-root}'
        MYSQL_USER: '${DB_USERNAME:-webrisk}'
        MYSQL_PASSWORD: '${DB_PASSWORD:-webrisk}'
        MYSQL_DATABASE: '${DB_PASSWORD:-webrisk}'
      volumes:
        - mysqldata:/var/lib/mysql
      ports:
        - "${DB_PORT:-3306}:3306"
volumes:
  mysqldata: {}